version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/dysh
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/run_build.sh
      timeout: 500
      runas: root
  ApplicationStart:
    - location: scripts/run_docker.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root