version: '3.4'

services:
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: stevef2257/dysh-frontend:latest
    ports:
      - 80:80
    networks:
      - dysh-network
  backend:
    # depends_on:
    #   - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: stevef2257/dysh-backend:latest
    environment:
      - MONGODB_URL=$MONGODB_URL
      - ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
      - REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
      - BACKEND_PORT=$BACKEND_PORT
    # environment:
      # MONGODB_URL: mongodb://db:27017/dysh
    networks:
      - dysh-network
# uncomment to run a mongo container and connect to it using the commented out environment variable
#   db:
#     image: mongo:6.0.4
#     ports:
#       - 27017:27017
#     volumes:
#       - dysh:/data/db
    
# volumes:
#   dysh:

networks:
  dysh-network: