version: '3.4'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports: 
      - 3000:80

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MONGODB_URL: mongodb://db/dysh 
    ports:
      - 5000:5000
      
  db:
    image: mongo:6.0.4
    ports:
      - 27017:27017
    volumes:
      - dysh:/data/db
      
volumes:
  dysh: 