version: '3.4'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    networks:
      - dysh-network
  backend:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MONGODB_URL: mongodb://db:27017/dysh
    ports:
      - 5000:5000
    networks:
      - dysh-network
  db:
    image: mongo:6.0.4
    ports:
      - 27017:27017
    volumes:
      - dysh:/data/db
    networks:
      - dysh-network
    
volumes:
  dysh:

networks:
  dysh-network: