version: '3.4'

services:
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    networks:
      - dysh-network
  backend:
    # depends_on:
    #   - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    # environment:
      # MONGODB_URL: mongodb://db:27017/dysh
    networks:
      - dysh-network
# uncomment to run a mongo container and connect to it using the commented out environment variable
#   db:
#     image: mongo:6.0.4
#     ports:
#       - 27017:27017
#     volumes:
#       - dysh:/data/db
    
# volumes:
#   dysh:

networks:
  dysh-network: