version: '3.4'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:80
    networks:
      - dysh-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URL:mongodb://db:27017/dysh
    networks:
      - dysh-network
  db:
    image: mongo:6.0.4
    ports:
      - 27017:27017
    volumes:
      - dysh:/data/db
volumes:
  dysh:

networks:
  dysh-network: