###authentication stuff
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email":"steve",
    "password":"password123"
}

###

DELETE http://localhost:5000/auth/logout
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxMjY1NSwiZXhwIjoxNjc2MDE2MjU1fQ.1y9wQyhZ2n1xLqK5D76a_zlTSdKXyXHgQURwcmfsmLc",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxMjY1NX0.3-Tcr6gB9wY62JzrBNCyjTv4BUyNLm9rwM18yf2MJLo"
}

###

POST http://localhost:5000/auth/refresh
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxMjY1NSwiZXhwIjoxNjc2MDE2MjU1fQ.1y9wQyhZ2n1xLqK5D76a_zlTSdKXyXHgQURwcmfsmLc",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxMjY1NX0.3-Tcr6gB9wY62JzrBNCyjTv4BUyNLm9rwM18yf2MJLo"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"steve",
    "password":"password123"
}

###

POST http://localhost:5000/auth/valid
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxMjY1NSwiZXhwIjoxNjc2MDE2MjU1fQ.1y9wQyhZ2n1xLqK5D76a_zlTSdKXyXHgQURwcmfsmLc",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxMjY1NX0.3-Tcr6gB9wY62JzrBNCyjTv4BUyNLm9rwM18yf2MJLo"
}
### ===========================================================================================

### /history endpoints
POST http://localhost:5000/api/history/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxMjY1NSwiZXhwIjoxNjc2MDE2MjU1fQ.1y9wQyhZ2n1xLqK5D76a_zlTSdKXyXHgQURwcmfsmLc

{
  "recipeID" :"63abeb6d75a5ef02d53fcbdb"
}

###
DELETE http://localhost:5000/api/history
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxMjY1NSwiZXhwIjoxNjc2MDE2MjU1fQ.1y9wQyhZ2n1xLqK5D76a_zlTSdKXyXHgQURwcmfsmLc

{
  "recipeID" :"63abeb6d75a5ef02d53fcbdb"
}

###
GET http://localhost:5000/api/history
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxMDYzMywiZXhwIjoxNjc2MDE0MjMzfQ.PYyTnNVw-uPxIH2dq4iB8KZNhrJHhl_MSPnCdC9IXLk
