###authentication stuff
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email":"steve",
    "password":"password123"
}

###

DELETE http://localhost:5000/auth/logout
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxOTkzNywiZXhwIjoxNjc2MDIzNTM3fQ.tvp5jC46AAYmZ65S-J6JkvW-yu6WshJLwIXNRy2wGEo",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxOTkzN30.lg2Ov9qSksURXLBGpLQqIpp0CMR9fli6x-I7faZWi1o"
}
###

POST http://localhost:5000/auth/refresh
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxOTkzNywiZXhwIjoxNjc2MDIzNTM3fQ.tvp5jC46AAYmZ65S-J6JkvW-yu6WshJLwIXNRy2wGEo",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxNjE0MX0.Xbrv_OmS3p9mNXZegY1VDb1-tsZ_Cz7k4meFXybMp6I"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"steve",
    "password":"password123"
}

###

POST http://localhost:5000/auth/valid
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxOTkzNywiZXhwIjoxNjc2MDIzNTM3fQ.tvp5jC46AAYmZ65S-J6JkvW-yu6WshJLwIXNRy2wGEo",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxNjA2MX0.htoWNVgXpV1VGKS8fSp4s_ZJrx5bJpOSRJ8Xpx333b4"
}
### ==================================================================================================
### /history endpoints
### ==================================================================================================
GET http://localhost:5000/api/history
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxOTkzNywiZXhwIjoxNjc2MDIzNTM3fQ.tvp5jC46AAYmZ65S-J6JkvW-yu6WshJLwIXNRy2wGEo

###

POST http://localhost:5000/api/history/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxOTkzNywiZXhwIjoxNjc2MDIzNTM3fQ.tvp5jC46AAYmZ65S-J6JkvW-yu6WshJLwIXNRy2wGEo

{
  "recipeID" :"63abeb6d75a5ef02d53fcbdb"
}

###
DELETE http://localhost:5000/api/history
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxOTkzNywiZXhwIjoxNjc2MDIzNTM3fQ.tvp5jC46AAYmZ65S-J6JkvW-yu6WshJLwIXNRy2wGEo

{
  "recipeID" :"63abeb6d75a5ef02d53fcbdb"
}
### ==================================================================================================
### /favorites endpoints
### ==================================================================================================
GET http://localhost:5000/api/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxOTkzNywiZXhwIjoxNjc2MDIzNTM3fQ.tvp5jC46AAYmZ65S-J6JkvW-yu6WshJLwIXNRy2wGEo

###

POST http://localhost:5000/api/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxOTkzNywiZXhwIjoxNjc2MDIzNTM3fQ.tvp5jC46AAYmZ65S-J6JkvW-yu6WshJLwIXNRy2wGEo

{
  "recipeID" :"63abeb6d75a5ef02d53fcbdb"
}

###

DELETE http://localhost:5000/api/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTVlNDg5YTUzZTJjMWViYzhlZDMyNyIsImlhdCI6MTY3NjAxOTkzNywiZXhwIjoxNjc2MDIzNTM3fQ.tvp5jC46AAYmZ65S-J6JkvW-yu6WshJLwIXNRy2wGEo

{
  "recipeID" :"63abeb6d75a5ef02d53fcbdb"
}